### ESPHome package: helper services for manual fan speed control

globals:
  - id: last_mode
    type: int
    restore_value: no
    initial_value: '-1'

  - id: mode_timer
    type: int
    restore_value: no
    initial_value: '0'

api:
  services:
    - service: set_fan_speed
      variables:
        fan_speed: int
      then:
        - if:
            condition:
              lambda: 'return fan_speed >= 0 && fan_speed <= 6;'
            then:
              - if:
                  condition:
                    lambda: 'return id(mode_timer) == 0;'
                  then:
                    - logger.log: "tion_set_fan_speed: First set_fan_speed call detected, setting first speed, waiting for second ..."
                    - globals.set:
                        id: last_mode
                        value: !lambda 'return fan_speed;'
                    - number.set:
                        id: max_fan_speed
                        value: !lambda 'return fan_speed;'
                    - number.set:
                        id: min_fan_speed
                        value: !lambda 'return fan_speed;'
                    - globals.set: { id: mode_timer, value: "1" }
                  else:
                    - logger.log: "tion_set_fan_speed: Second set_fan_speed call detected, setting range"
                    - number.set:
                        id: min_fan_speed
                        value: !lambda 'return std::min<int>(static_cast<int>(id(last_mode)), static_cast<int>(fan_speed));'
                    - number.set:
                        id: max_fan_speed
                        value: !lambda 'return std::max<int>(static_cast<int>(id(last_mode)), static_cast<int>(fan_speed));'
                    - globals.set: { id: mode_timer, value: "0" }
              - logger.log:
                  format: "Fan speed set to %d"
                  args: [ 'fan_speed' ]
            else:
              - logger.log:
                  level: ERROR
                  format: "Invalid fan speed value: %d"
                  args: [ 'fan_speed' ]

interval:
  - interval: 1s
    id: mode_timeout
    then:
      - if:
          condition:
            lambda: 'return id(mode_timer) > 0;'
          then:
            - globals.set:
                id: mode_timer
                value: !lambda 'return id(mode_timer) + 1;'
            - if:
                condition:
                  lambda: 'return id(mode_timer) >= 4;'
                then:
                  - logger.log: "tion_set_fan_speed: No second set_fan_speed call, keep fixed speed"
                  - globals.set: { id: mode_timer, value: "0" }
            - logger.log:
                format: "Timer set to %d"
                args: [ 'id(mode_timer)' ]
