# Расширение конфигурации ESPHOME для устройства Тион (https://github.com/dentra/esphome-tion)
#
# substitutions:
#   # Добавьте данную подстановку с указанием имени сенсора CO2 в раздел substitutions
#   auto_mode_co2_sensor: sensor.chrn_kitchen_co2
#
# packages:
#   # Добавьте данный пакет в раздел packages
#   tion_auto_mode:
#     url: https://github.com/dima11235/esphome-tion-ha-lovelace
#     files:
#       - esphome/tion_auto_mode.yaml
#

climate:
  - platform: pid
    id: pid_co2
    internal: true
    name: "PID CO2 Controller"
    sensor: current_co2
    default_target_temperature: 750
    cool_output: output_fan_speed
    control_parameters:
      ki: 0.00001
      kd: 0.0
      max_integral: 0.0 # Устраняет инерцию управления при длительном нахождении значения CO2 ниже целевого уровня
      kp: 0.005 # Переход на следующую скорость при повышении уровня CO2 на 25 ppm
      min_integral: -0.167 # Максимальное дополнительное повышение скорости на 1 от интегральной составляющей
      output_averaging_samples: 3


output:
  # Apply Fan Speed recommended by PID controller in Auto Mode
  - platform: template
    id: output_fan_speed
    type: float
    write_action:
      - logger.log: "output_fan_speed: write_action"
      - if:
          condition:
            and:
              - switch.is_on: power_mode
          then:
            - if:
                condition:
                  switch.is_on: silent_mode
                then:
                  - script.execute:
                      id: set_fan_speed
                      fan_speed: 1
                else:
                  - script.execute:
                      id: set_fan_speed
                      fan_speed: !lambda 'return min(max(round(6*state), id(min_fan_speed).state), id(max_fan_speed).state);'


script:
  # Script for setting the fan speed 0-6
  - id: set_fan_speed
    parameters:
      fan_speed: int
    then:
        - logger.log: "set_fan_speed"
        - if:
            condition:
              lambda: 'return fan_speed != int(id(current_fan_speed).state);'
            then:
              # Инициализация задержки чтения конфигурации с бризера для исключения конфликтов с выполняемой командой
              - globals.set:
                  id: sync_timer
                  value: '0'
              - component.update: sync_state

              # Выполнение команды
              - if:
                  condition: 
                    lambda: 'return fan_speed == 0;'
                  then:
                    climate.control:
                      id: tion_climate
                      mode: 'OFF'
                  else:
                    if:
                      condition: 
                        switch.is_on: heater_mode
                      then:
                        climate.control:
                          id: tion_climate
                          mode: 'HEAT'
                          custom_fan_mode: !lambda 'return to_string(fan_speed);'
                      else:
                        climate.control:
                          id: tion_climate
                          mode: 'FAN_ONLY'
                          custom_fan_mode: !lambda 'return to_string(fan_speed);'


sensor:
  # Current Fan Speed (0-6)
  - platform: tion
    type: fan_speed
    id: current_fan_speed
    name: "Fan Speed"
    icon: "mdi:fan"
    state_class: "measurement"
    accuracy_decimals: 0
    internal: false
    filters:
      - delta: 1.0
    on_value:
      - logger.log: "sensor.current_fan_speed: on_value"

            
  # Current CO2 level from external sensor in Home Assistant
  - platform: homeassistant
    name: "Current CO2"
    id: current_co2
    entity_id: ${auto_mode_co2_sensor}
    unit_of_measurement: "ppm"
    icon: "mdi:molecule-co2"
    device_class: "carbon_dioxide"
    state_class: "measurement"
    accuracy_decimals: 0
    internal: false


switch:
  # Power mode
  - platform: template
    name: "Power Mode"
    icon: "mdi:power"
    id: power_mode
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - logger.log: "switch.power_mode: turn_on_action"
      - globals.set: # Инициализация задержки чтения конфигурации с бризера для исключения конфликтов с выполняемой командой
          id: sync_timer
          value: '0'
      - component.update: sync_state
      - if:
          condition: 
            lambda: 'return id(max_fan_speed).state == 0;'
          then:
            - number.set:
                id: max_fan_speed
                value: !lambda 'return max(1, int(id(current_fan_speed).state));'
            - number.set:
                id: min_fan_speed
                value: !lambda 'return max(1, int(id(current_fan_speed).state));'
            - script.execute:
                id: set_fan_speed
                fan_speed: !lambda 'return max(1, int(id(current_fan_speed).state));'
      - if:
          condition: 
            lambda: 'return id(min_fan_speed).state != id(max_fan_speed).state;'
          then:
            - climate.control:
                id: pid_co2
                mode: 'COOL'
          else:
            - climate.control:
                id: pid_co2
                mode: 'OFF'
    turn_off_action:
      - logger.log: "switch.power_mode: turn_off_action"
      - globals.set: # Инициализация задержки чтения конфигурации с бризера для исключения конфликтов с выполняемой командой
          id: sync_timer
          value: '0'
      - component.update: sync_state
      - climate.control:
          id: pid_co2
          mode: 'OFF'
      - climate.control:
          id: tion_climate
          mode: 'OFF'

  # Heater mode
  - platform: tion
    type: heater
    name: "Heater Mode"
    icon: "mdi:fire"
    id: heater_mode

  # Silent mode (force Fan Speed 1 in Auto Mode)
  - platform: template
    name: "Silent Mode"
    icon: "mdi:weather-night"
    id: silent_mode
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - logger.log: "switch.silent_mode: turn_on_action"
      - if:
          condition: 
            switch.is_on: power_mode
          then:
            - script.execute:
                id: set_fan_speed
                fan_speed: 1
    on_turn_off:
      - logger.log: "switch.silent_mode: turn_off_action"
      - if:
          condition: 
            switch.is_on: power_mode
          then:
            - script.execute:
                id: set_fan_speed
                fan_speed: !lambda 'return id(min_fan_speed).state;'


number:
  # Heater temperature
  - platform: template
    name: "Heater Temperature"
    icon: "mdi:thermometer"
    id: heater_temperature
    unit_of_measurement: "°C"
    device_class: "temperature"
    min_value: 0
    max_value: 30
    step: 1
    lambda: 'return id(tion_climate).target_temperature;'
    update_interval: 15s
    set_action:
      - logger.log: "number.heater_temperature: set_action"

      # Инициализация задержки чтения конфигурации с бризера для исключения конфликтов с выполняемой командой
      - globals.set:
          id: sync_timer
          value: '0'
      - component.update: sync_state

      - climate.control:
          id: tion_climate
          target_temperature: !lambda 'return x;'

  # Target CO2 level in Auto Mode
  - platform: template
    name: "Target CO2"
    id: target_co2
    unit_of_measurement: "ppm"
    icon: "mdi:molecule-co2"
    device_class: "carbon_dioxide"
    min_value: 400
    max_value: 1200
    step: 50
    optimistic: true
    restore_value: true
    initial_value: 750
    set_action:
      - logger.log: "tion_auto_mode: number.target_co2: set_action"
      - if:
          condition: 
            lambda: 'return x != id(pid_co2).target_temperature;'
          then:
            - climate.control:
                id: pid_co2
                target_temperature: !lambda 'return x;'


  # Minimum fan speed in Auto Mode
  - platform: template
    name: "Min Fan Speed"
    icon: "mdi:fan"
    id: min_fan_speed
    min_value: 0
    max_value: 6
    step: 1
    optimistic: true
    restore_value: true
    initial_value: 1
    set_action:
      - logger.log: "tion_auto_mode: number.min_fan_speed: set_action"
      - if:
          condition: 
            lambda: 'return x > id(max_fan_speed).state;'
          then:
            - number.set:
                id: max_fan_speed
                value: !lambda 'return x;'
      - if:
          condition:
            and:
              - switch.is_on: power_mode
              - switch.is_off: silent_mode
              - lambda: 'return x > int(id(current_fan_speed).state);'
          then:
            - script.execute:
                id: set_fan_speed
                fan_speed: !lambda 'return x;'

  # Maximum fan speed in Auto Mode
  - platform: template
    name: "Max Fan Speed"
    icon: "mdi:fan"
    id: max_fan_speed
    min_value: 0
    max_value: 6
    step: 1
    optimistic: true
    restore_value: true
    initial_value: 2
    set_action:
      - logger.log: "tion_auto_mode: number.max_fan_speed: set_action"
      - if:
          condition: 
            lambda: 'return x < id(min_fan_speed).state;'
          then:
            - number.set:
                id: min_fan_speed
                value: !lambda 'return x;'
      - if:
          condition: 
            and:
              - switch.is_on: power_mode
              - switch.is_off: silent_mode
              - lambda: 'return x < int(id(current_fan_speed).state);'
          then:
            - script.execute:
                id: set_fan_speed
                fan_speed: !lambda 'return x;'
         

globals:
  - id: sync_timer
    type: int
    restore_value: no
    initial_value: '0'


interval:
  - interval: 15s
    id: sync_state
    then:
      - globals.set:
          id: sync_timer
          value: !lambda 'return id(sync_timer) + 1;'
      - if:
          condition:
            lambda: 'return id(sync_timer) < 3;' #Задержка 15 сек на выполнение операций после выполнения команды из интерфейса
          then:
            - logger.log:
                format: "tion_auto_mode: sync state: skipping [%d]"
                args: [ 'id(sync_timer)' ]
          else:
            - logger.log:
                format: "tion_auto_mode: sync state: syncing [%d]"
                args: [ 'id(sync_timer)' ]
            # Установка автоматического режима
            - if:
                condition: 
                  lambda: 'return id(min_fan_speed).state != id(max_fan_speed).state;' # Включение регулятора автоматического режима
                then:
                  - if:
                      condition: 
                        and:
                          - switch.is_on: power_mode
                          - lambda: 'return id(pid_co2).mode != CLIMATE_MODE_COOL;'
                      then:
                        - climate.control:
                            id: pid_co2
                            mode: 'COOL'
                        - logger.log: "tion_auto_mode: sync state: turn PID on"
                else:
                  # Отключение регулятора автоматического режима
                  - if:
                      condition: 
                        or:
                          - switch.is_off: power_mode
                          - lambda: 'return id(pid_co2).mode != CLIMATE_MODE_OFF;' 
                      then:
                        - climate.control:
                            id: pid_co2
                            mode: 'OFF'
                        - logger.log: "tion_auto_mode: sync state: turn PID off"
            # Установка статуса включения бризера
            - if: 
                condition: 
                  and:
                    - lambda: 'return id(tion_climate).mode != CLIMATE_MODE_OFF;' 
                    - switch.is_off: power_mode
                then:
                  - logger.log: "tion_auto_mode: sync state: turn Power Mode on"
                  - switch.turn_on: power_mode
